# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"gen_bio_vocab": "00_core.ipynb",
         "pred_vs_truth": "00_core.ipynb",
         "raw2token": "00_core.ipynb",
         "token2hot": "00_core.ipynb",
         "hot2token": "00_core.ipynb",
         "prep_seqs": "00_core.ipynb",
         "DnaDataset": "00_core.ipynb",
         "StepByStep": "00_core.ipynb",
         "generate_Seqs_Exp_Dataset": "00_core.ipynb",
         "baseline_cnn": "01_models.ipynb"}

modules = ["core.py",
           "models.py"]

doc_url = "https://cjgo.github.io/bionlp/"

git_url = "https://github.com/cjgo/bionlp/tree/master/"

def custom_doc_links(name): return None
