# AUTOGENERATED! DO NOT EDIT! File to edit: 01_models.ipynb (unless otherwise specified).

__all__ = ['baseline_cnn']

# Cell
from bionlp_imports import *
from .core import *

# Cell
class baseline_cnn(torch.nn.Module):
    """ simplest CNN """
    def __init__(self):
        super().__init__()
        self.conv1 = nn.LazyConv1d(out_channels=10, kernel_size=5)
        self.flatten = nn.Flatten()
        self.linear1 = nn.LazyLinear(1)

    def forward(self,x):
        x = self.conv1(x)
        x = self.flatten(x)
        x = self.linear1(x)
        return x.flatten()
